server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      service-discovery:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: PreserveHostHeader
      routes:
        - id: loan-service
          uri: http://loan-service
          predicates:
            - Path=/api/v1/loan-service/**
        - id: loan-group-service
          uri: http://loan-group-service
          predicates:
            - Path=/api/v1/loan-group-service/**
          filters:
            - RewritePath=/api/v1/loan-group-service/(?<segment>.*), /api/v1/loan-group-service/${segment}
        - id: user-service
          uri: http://user-service
          predicates:
            - Path=/api/v1/user-service/**
        - id: investment-service
          uri: http://invest-service
          predicates:
            - Path=/api/v1/invest-service/**
        - id: repayment-service
          uri: http://repayment-service
          predicates:
            - Path=/api/v1/repayment-service/**
        - id: chatbot-proxy-service
          uri: http://chatbot-proxy
          predicates:
            - Path=/chat/**
        - id: credit-proxy-service
          uri: http://credit-proxy
          predicates:
            - Path=/api/v1/credit/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://billit.kro.kr"
              #- "https://billit.kro.kr"
              - "http://34.44.246.168/"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    hostname: gateway-service
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true

